version: '3'
services:
  postgres:
    image: cazmaars/docker:dr-1.0
    ports:
      - 4007:3000
  postgres1:
    image: cazmaars/docker:dr-1.0
    ports:
      - 4007:3000
  postgres2:
    image: cazmaars/docker:dr-1.345
    ports:
      - 4007:3000


